spring:
  application:
    name: main-service

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres-ewm-main-db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show-sql: false
        format_sql: true


server:
  port: 0

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
