services:
  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: ewm-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: stats-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  stats-server:
    container_name: stats-server
    ports:
        - "9090:9090"
    build: ./stats/stats-server
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:6543/stats-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345