spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      discovery.locator.enabled: true
      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**, /api/v1/users/**
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**, /api/v1/requests/**
        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/hit/**, /stats/**
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/**
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    routes:
      enabled: true

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG


