spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/**

server:
  port: 8080


