CREATE TABLE IF NOT EXISTS categories (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat     DOUBLE PRECISION NOT NULL,
    lon     DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation          TEXT,
    title               VARCHAR(128) NOT NULL,
    category_id         BIGINT,
    description         TEXT,
    created_on          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_date          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id        BIGINT NOT NULL,
    paid                BOOLEAN NOT NULL,
    participant_limit   BIGINT NOT NULL,
    published_on        TIMESTAMP WITHOUT TIME ZONE,
    request_moderation  BOOLEAN,
    location_id         BIGINT,
    state               VARCHAR(10) NOT NULL,
    FOREIGN KEY (category_id)  REFERENCES categories(id),
    FOREIGN KEY (location_id)  REFERENCES locations(id)
);
CREATE TABLE IF NOT EXISTS compilations (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned  BOOLEAN NOT NULL,
    title   VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id   BIGINT NOT NULL,
    event_id         BIGINT NOT NULL,
    PRIMARY KEY (compilation_id, event_id),
    FOREIGN KEY (compilation_id) REFERENCES compilations(id),
    FOREIGN KEY (event_id)       REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text        TEXT NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    author_id   BIGINT NOT NULL,
    event_id    BIGINT NOT NULL,
    FOREIGN KEY (event_id)  REFERENCES events(id)
);
